[package]
name = "tokio_shutdown"
version = "0.1.0"

license.workspace = true
authors.workspace = true
repository.workspace = true

edition.workspace = true
rust.workspace = true


[dependencies]
tokio = { version = "1", features = ["sync"] }
