[package]
name = "firmware_protocol"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
deku = { version = "0.15", default-features = false, features = ["alloc"] }
nalgebra = { version = "0.31", default-features = false }