name: Deployment
on:
  push:
    branches: [main]

jobs:
  docs:
    name: Deploy Docs to Github Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build Internal Documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --all-features --no-deps --document-private-items

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs
          folder: target/doc

  build_binary:
    name: Build Release Executables
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - runs-on: windows-latest
            name: windows-x64
          - runs-on: ubuntu-latest
            name: linux-x64
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build ${{ matrix.name }} release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}-binary
          path: |
            target/release/slimevr_overlay.exe
            target/release/slimevr_overlay

  pre-release:
    name: Pre-Release
    runs-on: ubuntu-latest
    needs: build_binary
    permissions:
      contents: write

    steps:
      - name: Download windows artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-x64-binary
      - name: Download linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-x64-binary

      - name: Download shared libs
        run: |
          wget https://github.com/ValveSoftware/openvr/raw/v1.16.8/lib/win64/openvr_api.lib
          wget https://github.com/ValveSoftware/openvr/raw/v1.16.8/bin/win64/openvr_api.dll
          wget https://github.com/ValveSoftware/openvr/raw/v1.16.8/lib/linux64/libopenvr_api.so

      - name: Create Windows Zip
        run: zip windows-x64.zip openvr_api.lib openvr_api.dll slimevr_overlay.exe

      - name: Create Linux Zip
        run: zip linux-x64.zip libopenvr_api.so slimevr_overlay

      - name: Create Overlay Release
        uses: "marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "overlay-latest"
          prerelease: true
          title: "Overlay - Latest Build"
          files: |
            windows-x64.zip
            linux-x64.zip
