name: Main CI
on: [pull_request]

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check

      - name: Clippy lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --all-features --all-targets --no-deps

  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check that docs build
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --all-features --no-deps --document-private-items

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features --all-targets
